travis:
  secure:
    BINSTAR_TOKEN: 0v/PG4wEkHckMmA6QWkeBHisNvDb3/4PFlbZIBMqfPzo+pj47IflCLwZ8leSAWj9IE89V/tE9vbeDebExekKc5LN9JCOATDU+Fv814gG9sEJJeSUufmJ5LE/dgPbxhLdGwX4UY71PIgM2eo4u5FsRfcQuzxYCarcSLvf1lu0OyKnocq7+hnkBlJbZ35sCAkJ+U+5PXRDgffjKbJXcpLC3WTRZRvHrZeSJ0NLdxQj9kC0LG/AAXfLqY0bCvPh6v9nq9DfPj50RYlt4zLoV3GHmHSpUbJo7TUwBBUp4yIs3rZ0lxXhFjwUvUOgN6Ltl0vhHwnXVkv//ZvsRkD0+CuI32hbNLB9NIjQv/yPVixhCQ5kyF+GVUduNZKzsfKcsLVd3wFlsOo7tswEqts9Cae2ayjMW65rGdW4WLbRmLjvkcucl7lzOD7GJhz16/3GIJgp1lPYa+YMHi5yri0jz69XZYHIr8a/7myIwrGRdo5bs+BRdNXwPSh8FL1H/Vw7Xt+YDK+kErJ2FsVv5KAwNKFZHte6cmHK3/0FDv/nzQQRuT0LzQIp+mU1C4MMM6KL+cI1nmjQXuShrFCZgpWYwuuhw02t07WYjOnpGp+xlsIt+Bn2Q3f9nyW8hPo0NfQmHC1yLWSW38h517gFzSvD3/pumPY6OVxx1t+mimyN8LciOqQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
