travis:
  secure:
    BINSTAR_TOKEN: AHv2a2d8sFR7faEHcN+6rAcEy5OVvo8DHdSlI7B3N1avMwLqqA5jbR5G/zNJ8wgbZpQIQzBUO/OGVxsPmI28YIzs04XKNYUNMgrmpE9KlQ2cfh8wavfvPY4GvQVkekKDeq/lW1XbzRexDdBC243TRpDXfq15/B+GKjF5IFt7kcMT9IwJZehAaaFz66jMIgvoPZY8Ivs+KSKBg0KZyuzMJfhcpyJO9YrGRKIXus0VPRkRFIRsvT9Yxjw6bQjDQOROPHhsUGlBRMUYYRdS7UH0zlxqPqOpo66CvUYpPCtqQA1PJOZyNBgrmWZcNZnyQMGsFQXVBTqD40GyzAarNdzwgE1GO8nrG139jIByuW7w1soA2jcGnx/srNNEhvv2eqpJshKe3LRFWBaLHDSHrHedpM0x5HxigufTWrDyCULkTNlwqloh1z6F6QB4Qn4oA/XWfKaQ2UKXXjVDgyylgsJNUspkLhKHX+Qe+y2M88oNvVK2GEaABruILR/2qmjW8OCQ36vtk54P83He2CmK2nq/riaZ7eyaACHbkLs335gqgKIF374qqwwi72dRZcf37GROft9Eh1BdI8iqzf62ZR5G1I4IEBZPi8XzV60mhWw1y6q9TWkdgN6DPdJYm7c+E5BRTEMNlMogAjE9r6RtlQRaR3UO0A0UAiRgXXqO37yuwoM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
