travis:
  secure:
    BINSTAR_TOKEN: y0aW5lT6uJBL2t/cluW5xJE3bwbEkPpGCVxDWiqHwgr2VauHfIATwBQufzU8fWJiqf43aoeiYkZW0HIhPx0Tbhbj4pRrIsloB9YB3G8k8MStM90RmX6/4Gzo7d3h/5Nvq4YPF+rctrJ/M4yBgyC3/7+62FYAP09ruQsmudW9ZB0ELqDaawchRhVGdzY5jfyqKWWZ3E61rmdDbLW1hUoiLpmcKda1wkG3SdnipAw2xbLiqRJqzzq+DFxxWo2v8fjjn+H2zEqeVNUkixXMXmnE+0FZ/f8I+gAvP2Z19ykk9VZW2whvcyl7bBk9cwFC13LC1LlQ2JlD34RZQ6jiSrK5lJHMExNjONSpBwLlwoixrjFKrDGyP7rP25fHEAv/1OoejxX/Gt7ulgioMxA1YnKxpgDZ0lHeL5lQS15p9DTMVXG3EMl35RDEf6H80jCqcnTMfnbRIqA0PVLs2afleizDeYKwb46SZOlt0ehBWPGF7yU2DWBhyfalsxj8fDwSxw3cdQXAwJ0YFokRtxCx2j8vKMwv7YeJ6lM15757+HeDyyNgonGaCDORxO3VgpLKZQr1MfzqM+O/F5Ezhg+rgJCjjMzcTKPzr+LV9nyf0y3X+3VrE5nkKAHRhNvDw9SeiJmL9KfoSuSklMMaOEqhqtvrIVyKteTnThFQFh/f81PPZpg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
